import {
  createTemplateEditorSchema,
  defineTemplateEditorConfig,
} from "@/features/editor/config/templateEditorSchema";

export const hotelTemplateEditorConfig = defineTemplateEditorConfig({
  id: "hotel-template",
  label: "Hotel",
  sections: [
    { id: "cover", label: "Hotel cover", description: "Update the hotel cover image.", tab: "profile", fields: ["bannerUrl"] },
    { id: "identity", label: "Hotel identity", description: "Edit logo, hotel name, and tagline.", tab: "profile", fields: ["avatarUrl", "name", "role"] },
    { id: "bio", label: "About the hotel", description: "Edit the hotel description.", tab: "profile", fields: ["bio"] },
    { id: "contact", label: "Booking and location", description: "Edit booking contacts, website, and address.", tab: "profile", fields: ["emails", "phones", "website", "location"] },
    { id: "socials", label: "Social and booking links", description: "Manage social and booking platforms.", tab: "links", fields: ["socials", "socialOrder"] },
    { id: "gallery", label: "Gallery", description: "Manage hotel photography.", tab: "gallery", fields: ["gallery"] },
    { id: "sections", label: "Custom sections", description: "Add extra hotel content.", tab: "sections", fields: ["custom_sections"] },
  ],
  defaults: {
    name: "",
    avatarUrl: "",
    bannerUrl:
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&auto=format&fit=crop&q=80",
    role: "L'élégance marocaine, entre Marrakech et l'Atlas",
    bio: "À quelques minutes de la médina, un resort contemporain inspiré par l'hospitalité marocaine.",
    email: "reservations@grandamara.ma",
    phone: "+212 5 24 33 48 80",
    location: "Route de l'Ourika, Km 8, Marrakech 40000",
    website: "https://grandamara.ma",
    socials: {},
    socialOrder: [],
    gallery: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=500&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=500&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=500&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=500&auto=format&fit=crop&q=80",
    ],
    custom_sections: [],
    appearance: {},
  },
  editableFields: [
    "avatarUrl",
    "bannerUrl",
    "name",
    "role",
    "bio",
    "email",
    "phone",
    "emails",
    "phones",
    "socials",
    "gallery",
    "custom_sections",
  ],
  persistedFields: [
    "bannerUrl",
    "role",
    "bio",
    "email",
    "phone",
    "emails",
    "phones",
    "location",
    "website",
    "socials",
    "socialOrder",
    "gallery",
    "custom_sections",
    "appearance",
  ],
  schema: createTemplateEditorSchema(),
});
