import {
  createTemplateEditorSchema,
  defineTemplateEditorConfig,
} from "@/features/editor/config/templateEditorSchema";

export const buzzTemplateEditorConfig = defineTemplateEditorConfig({
  id: "buzz-template",
  label: "BuzzCard",
  sections: [
    { id: "cover", label: "Cover image", description: "Replace or remove the profile cover image.", tab: "profile", fields: ["bannerUrl"] },
    { id: "quote", label: "Quote", description: "Edit the short quote displayed over the cover.", tab: "profile", fields: ["quote"] },
    { id: "identity", label: "Profile identity", description: "Edit the avatar, full name, and professional role.", tab: "profile", fields: ["avatarUrl", "name", "role"] },
    { id: "contact", label: "Contact actions", description: "Edit phone, email, and website actions.", tab: "profile", fields: ["emails", "phones", "website"] },
    { id: "bio", label: "About", description: "Edit the biography displayed in the About card.", tab: "profile", fields: ["bio"] },
    { id: "socials", label: "Social links", description: "Add, remove, edit, or reorder social links.", tab: "links", fields: ["socials", "socialOrder"] },
    { id: "gallery", label: "Gallery", description: "Upload, replace, remove, or reorder gallery images.", tab: "gallery", fields: ["gallery"] },
    { id: "sections", label: "Custom sections", description: "Create and organize additional profile sections.", tab: "sections", fields: ["custom_sections"] },
  ],
  defaults: {
    name: "",
    avatarUrl: "",
    bannerUrl:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=85&w=1200&h=500",
    role: "Founder & Growth Strategist · Atlas Growth Studio",
    bio: "I help ambitious Moroccan brands turn clear positioning, strategic partnerships, and digital experiences into sustainable growth.",
    email: "yassine@atlasgrowth.studio",
    phone: "+212 6 64 28 91 40",
    quote: "Clarity creates momentum.",
    website: "https://atlasgrowth.studio",
    socials: {},
    socialOrder: [],
    gallery: [
      "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&q=85&w=1000",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=85&w=1000",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&q=85&w=1000",
    ],
    custom_sections: [],
    appearance: {},
  },
  editableFields: [
    "avatarUrl",
    "bannerUrl",
    "name",
    "role",
    "bio",
    "quote",
    "email",
    "phone",
    "emails",
    "phones",
    "website",
    "socials",
    "socialOrder",
    "gallery",
    "custom_sections",
  ],
  persistedFields: [
    "bannerUrl",
    "role",
    "bio",
    "email",
    "phone",
    "emails",
    "phones",
    "quote",
    "website",
    "socials",
    "socialOrder",
    "gallery",
    "custom_sections",
    "appearance",
  ],
  schema: createTemplateEditorSchema(),
});
