import * as z from "zod";
import {
  createTemplateEditorSchema,
  defineTemplateEditorConfig,
} from "@/features/editor/config/templateEditorSchema";

export const doctorTemplateEditorConfig = defineTemplateEditorConfig({
  id: "doctor-template",
  label: "Doctor",
  sections: [
    { id: "cover", label: "Cover image", description: "Update the clinic cover image.", tab: "profile", fields: ["bannerUrl"] },
    { id: "identity", label: "Doctor profile", description: "Edit portrait, name, and speciality.", tab: "profile", fields: ["avatarUrl", "name", "role"] },
    { id: "bio", label: "Professional overview", description: "Edit biography, education, and awards.", tab: "profile", fields: ["bio", "education", "awards"] },
    { id: "contact", label: "Contact information", description: "Edit phone, email, and clinic location.", tab: "profile", fields: ["emails", "phones", "location"] },
    {
      id: "services",
      label: "Services",
      description: "Edit the medical services shown on the profile.",
      tab: "configured",
      fields: Array.from({ length: 6 }, (_, index) => [`service_${index + 1}_title`, `service_${index + 1}_desc`]).flat(),
      controls: Array.from({ length: 6 }, (_, index) => [
        { name: `service_${index + 1}_title`, label: `Service ${index + 1} title` },
        { name: `service_${index + 1}_desc`, label: `Service ${index + 1} description`, type: "textarea", rows: 2 },
      ]).flat(),
    },
    { id: "socials", label: "Social links", description: "Manage the doctor's social profiles.", tab: "links", fields: ["socials", "socialOrder"] },
    { id: "gallery", label: "Gallery", description: "Manage clinic and practice photos.", tab: "gallery", fields: ["gallery"] },
    { id: "sections", label: "Custom sections", description: "Add extra professional content.", tab: "sections", fields: ["custom_sections"] },
  ],
  defaults: {
    name: "",
    avatarUrl: "",
    bannerUrl:
      "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=600&h=220",
    role: "MBBS · MD · Cardiologue",
    bio: "Plus de 14 ans d'excellence clinique en cardiologie diagnostique et soins préventifs.",
    email: "amina.elfassi@royale.ma",
    phone: "+212 6 61 23 45 67",
    location: "145 Boulevard d'Anfa, Bourgogne, Casablanca",
    education:
      "Doctorat en Médecine - Faculté de Médecine et de Pharmacie de Casablanca.\nSpécialisation en Cardiologie - Hôpital Universitaire Pitié-Salpêtrière, Paris.",
    awards:
      "Prix d'Excellence en Recherche Cardiologique (2020).\nMembre d'honneur de la Société Marocaine de Cardiologie.",
    kpiExp: "14+",
    kpiPatients: "2 800+",
    kpiSatisfaction: "98%",
    badge1: "Cardiologie",
    badge2: "Soins Préventifs",
    badge3: "ECG",
    socials: {},
    socialOrder: [],
    gallery: [
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=400&h=300",
      "https://images.unsplash.com/photo-1638202993928-7267aad84c31?auto=format&fit=crop&q=80&w=400&h=300",
      "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=400&h=300",
      "https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=400&h=300",
    ],
    custom_sections: [],
    appearance: {},
  },
  editableFields: [
    "avatarUrl",
    "bannerUrl",
    "name",
    "role",
    "bio",
    "email",
    "phone",
    "emails",
    "phones",
    "socials",
    "gallery",
    "custom_sections",
  ],
  persistedFields: [
    "bannerUrl",
    "role",
    "bio",
    "email",
    "phone",
    "emails",
    "phones",
    "location",
    "education",
    "awards",
    "kpiExp",
    "kpiPatients",
    "kpiSatisfaction",
    "badge1",
    "badge2",
    "badge3",
    "socials",
    "socialOrder",
    "gallery",
    "custom_sections",
    "appearance",
  ],
  dynamicFieldPatterns: [
    /^service_\d+_(title|desc)$/,
    /^testimonial_\d+_(text|author|date)$/,
    /^blog_\d+_(title|excerpt)$/,
  ],
  schema: createTemplateEditorSchema({
    education: z.string().max(10000).optional(),
    awards: z.string().max(10000).optional(),
    kpiExp: z.string().max(40).optional(),
    kpiPatients: z.string().max(40).optional(),
    kpiSatisfaction: z.string().max(40).optional(),
    badge1: z.string().max(80).optional(),
    badge2: z.string().max(80).optional(),
    badge3: z.string().max(80).optional(),
  }),
});
