import {
  createTemplateEditorSchema,
  defineTemplateEditorConfig,
} from "@/features/editor/config/templateEditorSchema";

export const coiffeurTemplateEditorConfig = defineTemplateEditorConfig({
  id: "coiffeur-template",
  label: "Coiffeur",
  sections: [
    { id: "cover", label: "Salon cover", description: "Update the salon cover image.", tab: "profile", fields: ["bannerUrl"] },
    { id: "identity", label: "Salon identity", description: "Edit portrait, name, and professional title.", tab: "profile", fields: ["avatarUrl", "name", "role"] },
    { id: "bio", label: "About the salon", description: "Edit the salon description.", tab: "profile", fields: ["bio"] },
    { id: "contact", label: "Contact and booking", description: "Edit phone, email, and salon location.", tab: "profile", fields: ["emails", "phones", "location"] },
    { id: "socials", label: "Social links", description: "Manage salon social profiles.", tab: "links", fields: ["socials", "socialOrder"] },
    { id: "gallery", label: "Gallery", description: "Manage hairstyle and salon photos.", tab: "gallery", fields: ["gallery"] },
    { id: "sections", label: "Custom sections", description: "Add extra salon content.", tab: "sections", fields: ["custom_sections"] },
  ],
  defaults: {
    name: "",
    avatarUrl: "",
    bannerUrl:
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=600&h=250",
    role: "Coiffeur-visagiste & Fondateur · Atelier Amine",
    bio: "Des coupes et des couleurs sur mesure, pensées pour votre visage, votre style et votre quotidien.",
    email: "bonjour@atelieramine.ma",
    phone: "+212 6 68 34 21 90",
    location: "34 Rue Ibn Aïcha, Guéliz, Marrakech",
    socials: {},
    socialOrder: [],
    gallery: [
      "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1675034743339-0b0747047727?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1620331311520-246422fd82f9?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80&w=800",
    ],
    custom_sections: [],
    appearance: {},
  },
  editableFields: [
    "avatarUrl",
    "bannerUrl",
    "name",
    "role",
    "bio",
    "email",
    "phone",
    "emails",
    "phones",
    "socials",
    "gallery",
    "custom_sections",
  ],
  persistedFields: [
    "bannerUrl",
    "role",
    "bio",
    "email",
    "phone",
    "emails",
    "phones",
    "location",
    "socials",
    "socialOrder",
    "gallery",
    "custom_sections",
    "appearance",
  ],
  schema: createTemplateEditorSchema(),
});
